### ISSUE TITLE
autoinsert plugin backspace bug

### ISSUE THREAD

**Issue by Jeddi212** [lite-xl/lite-xl-plugins#116]
lite-xl version : 2.0.5-luajit (from AUR)

For instance i have this text file like this
```
"A",
"B"
```

Then, when i use backspace (or ctrl + backspace), for deleting break line, from the B left doublequote 
```
 "B"
^ my cursor is here
```

expected
```
"A","B"
```

result
```
"A",B"
```
The left quotes of B is got deleted to.

<hr>

Another example

```
some_function("foo bar")
             ^ my cursor is between parentheses & quote
```

When i delete parentheses

expected
```
some_function"foo bar")
```

result
```
some_functionfoo bar")
```
The quote got deleted too.

**Comment by Guldoman** [comment]
Does 1ea1994c232d5fae868c7468ed44fed71baa5709 fix it?

**Comment by Jeddi212** [comment]
Yes, its fixed. Thanks @Guldoman
