### ISSUE TITLE
plugins\minimap.lua:467: attempt to index a nil value (local 'color')

### ISSUE THREAD

**Issue by techie-guy** [lite-xl/lite-xl-plugins#144]
Got this error, I don't know why?

The Full Error Message from ```error.txt```:
```
Error: ...l-v2.1.0-windows-x86_64\lite-xl\data/plugins\minimap.lua:467: attempt to index a nil value (local 'color')
stack traceback:
	...l-v2.1.0-windows-x86_64\lite-xl\data/plugins\minimap.lua:467: in function 'plugins.minimap.draw'
	...lite-xl-v2.1.0-windows-x86_64\lite-xl\data/core\view.lua:302: in function 'core.view.draw_scrollbar'
	...e-xl-v2.1.0-windows-x86_64\lite-xl\data/core\docview.lua:547: in upvalue 'old_draw'
	...1.0-windows-x86_64\lite-xl\data/plugins\linewrapping.lua:512: in function 'core.docview.draw'
	...lite-xl-v2.1.0-windows-x86_64\lite-xl\data/core\node.lua:588: in function 'core.node.draw'
	...lite-xl-v2.1.0-windows-x86_64\lite-xl\data/core\node.lua:32: in function 'core.node.propagate'
	...lite-xl-v2.1.0-windows-x86_64\lite-xl\data/core\node.lua:593: in function 'core.node.draw'
	...lite-xl-v2.1.0-windows-x86_64\lite-xl\data/core\node.lua:31: in function 'core.node.propagate'
	...lite-xl-v2.1.0-windows-x86_64\lite-xl\data/core\node.lua:593: in function 'core.node.draw'
	...lite-xl-v2.1.0-windows-x86_64\lite-xl\data/core\node.lua:32: in function 'core.node.propagate'
	...	(skipping 2 levels)
	...-xl-v2.1.0-windows-x86_64\lite-xl\data/core\rootview.lua:454: in upvalue 'root_view_draw'
	...te-xl-v2.1.0-windows-x86_64\lite-xl\data/widget/init.lua:1255: in upvalue 'draw'
	...1.0-windows-x86_64\lite-xl\data/plugins\autocomplete.lua:571: in upvalue 'root_view_draw'
	....1.0-windows-x86_64\lite-xl\data/plugins\contextmenu.lua:31: in upvalue 'root_view_draw'
	...-v2.1.0-windows-x86_64\lite-xl\data/plugins\treeview.lua:498: in function 'core.rootview.draw'
	...lite-xl-v2.1.0-windows-x86_64\lite-xl\data/core/init.lua:1340: in function 'core.step'
	...lite-xl-v2.1.0-windows-x86_64\lite-xl\data/core/init.lua:1384: in upvalue 'core_run'
	...-v2.1.0-windows-x86_64\lite-xl\data/plugins\settings.lua:1795: in function 'core.run'
	(...tail calls...)
	[string "local core..."]:9: in function <[string "local core..."]:2>
	[C]: in function 'xpcall'
	[string "local core..."]:2: in main chunk
```

Also, how can I change the cursor shape?

**Comment by Guldoman** [comment]
Did you find out what the problem was?

**Comment by techie-guy** [comment]
no, I just removed that plugin

**Comment by Guldoman** [comment]
That error could be caused by having an invalid `style.syntax["normal"]`. Do you customize it?

**Comment by techie-guy** [comment]
No

**Comment by suntorytimed** [comment]
Same issue when installing lite-xl including lite-xl-plugins on openSUSE Tumbleweed.

**Comment by Guldoman** [comment]
Same backtrace?
> installing ... lite-xl-plugins on openSUSE Tumbleweed.

Please don't install those kind of packages. I'd even say to please ask the packager to remove it.
You're not supposed to install tons of plugins you won't use as they can potentially conflict with each other.
A better solution would be to ask your packagers to provide packages for https://github.com/lite-xl/lite-xl-plugin-manager.

**Comment by suntorytimed** [comment]
@Guldoman thanks for the advise. Packaging lite-xl-plugin-manager for Tumbleweed is what I did now. Just a small issue with the binary remaining, but it should be possible to have it in the distribution soon.

**Comment by Guldoman** [comment]
> @Guldoman thanks for the advise. Packaging lite-xl-plugin-manager for Tumbleweed is what I did now. Just a small issue with the binary remaining, but it should be possible to have it in the distribution soon.

Awesome!

@sbradnick users that install that package will not be aware of the list of plugins and the possible conflicts.
For example how would they go and replace the `nonicons` plugin with the `nerdicons` one? Will they know that they have to uninstall `lite-xl-plugins`?
Using `lpm`, will they be able to do that?

A better thing to package would be `lite-xl-addons`, which contains the plugins that we ship with the `addons` version of Lite XL (which provides the gear icon thing).
But be aware that in a future version we'll not ship it anymore, but provide a metaplugin that will install them with `lpm`.

About `nonicons` not including the font, we have a change in a PR that will make `lpm` install it in the proper location.

Anyways, the additions to `nonicons` you're doing in the package look good, are you interested in opening a pull request?

Also this
```
Going back to commit from last release timeframe, more current ones exhibit high CPU usage and poor UI rendering speed
```
from the package changelog looks interesting (and highlight the issue I have with such a package). Would you mind expanding on it in a new issue?

**Comment by sbradnick** [comment]
Historically, as I found and lightly used Lite-XL - this setup (with the `-plugins` package) is what worked for me. If `lpm` does 99% of what `-plugins` does I'm fine w/ having `lpm` remove `-plugins` if someone installs `lite-xl-plugin-manager`.

As it stands now, `-colors`, `-widgets` and `-plugins` are just "Suggests" for the `lite-xl` package so someone would have to explicitly choose to install them. I could even do a `lite-xl` "Recommends" `lite-xl-plugin-manager` and shift towards managing `-colors` and `-plugins` via it (i.e. removing those as RPM offerings via package management).

I'm honestly not sure where `-widgets` fits in to the current state of `Lite-XL`, I added it when it was suggested but I don't heavily use Lite-XL enough presently to _know_ which packages are REQUIRED vs 'nice to have'. As I said, this setup is what worked for me and gave me an experience I was expecting out-of-the-box.

Unfortunately, the last set of updates that git pulled in - had oddly poor performance I don't get from something closer to the last release version (maybe the day 2.1.1 was released).

**Comment by sbradnick** [comment]
> A better thing to package would be lite-xl-addons, which contains the plugins that we ship with the addons version of Lite XL (which provides the gear icon thing).

I don't see a `lite-xl-addons` repo under [lite-xl/repositories](https://github.com/orgs/lite-xl/repositories)

> But be aware that in a future version we'll not ship it anymore, but provide a metaplugin that will install them with lpm.

Which would be what?

I've got `lite-xl-plugin-manager` installed and `lpm` seems to work, I can run `lpm plugin install nonicons` and it seems to install but the .ttf/.otf isn't present (known issue as you described :smile:) but doing the same for `nerdfonts` throws an error. And right clicking on nonicons in the GUI plugin manager throws an error as well.

![2023-08-10-145000_1480x400_scrot](https://github.com/lite-xl/lite-xl-plugins/assets/84082961/4dc9433b-920b-44a3-ad77-6ab49edb419e)



I realize that Lite-XL is still being developed, but this type of churn in best-practices (and what's supposed to be used where) is why I've generally stepped away from it. It's a beautiful editor and seems highly functional but the care-and-feeding to get it setup has pushed me away since I can't constantly watch these evolutionary changes. I think it's great/fine for someone closely following it via GitHub and building locally - but it's a bit of a bear to do in a package management sense to provide a base-config that would be a good 'getting started with Lite-XL' setup. But I'm happy to continue on with what we've got in a base `lite-xl` package supplemented with `lpm`.

**Comment by adamharrison** [comment]
I'm on vacation as of today, but should have some time to validate those two PRs sometime early next week.

**Comment by sbradnick** [comment]
> Look at our release notes. It's not a repo, it was just a name suggestion for the package that would bundle addons.

That's fair. Also part of the reason I _kinda_ gave up on it because there were all these `lite-xl-<something>` items popping up and since my attention isn't focused on Lite-XL exclusively (no one's fault in the slightest or a Lite-XL dev problem), it became easier to focus on a type of 'well, it works for me / how I expected' scenario when someone would do: `sudo zypper in --details lite-xl`. It's feeling like `lite-xl-plugin-manager` alleviates all those 'package manager' problems, which is great! Trying to strike a balance between 'I want to use my package manager' and 'I need to `git clone` and compile' [any|every]thing to use Lite-XL.

> We're planning to ship Lite XL with lpm bundled in. On first start it will ask if you want to install a "starter pack" of plugins, which will include those in the addons version.

ok, that explains why it seems like _maybe_ it wants to install `/home/scott/.config/lite-xl/plugins/plugin_manager/lpm.x86_64-linux` when I do my initial `lpm plugin install ...`.

**Comment by adamharrison** [comment]
> > Look at our release notes. It's not 
> That's fair. Also part of the reason I _kinda_ gave up on it because there were all these `lite-xl-<something>` items popping up and since my attention isn't focused on Lite-XL exclusively (no one's fault in the slightest or a Lite-XL dev problem), it became easier to focus on a type of 'well, it works for me / how I expected' scenario when someone would do: `sudo zypper in --details lite-xl`. It's feeling like `lite-xl-plugin-manager` alleviates all those 'package manager' problems, which is great! Trying to strike a balance between 'I want to use my package manager' and 'I need to `git clone` and compile' [any|every]thing to use Lite-XL.

Yeah, agree with this. In future it'll be exactly one release per platform. 

> ok, that explains why it seems like _maybe_ it wants to install `/home/scott/.config/lite-xl/plugins/plugin_manager/lpm.x86_64-linux` when I do my initial `lpm plugin install ...`.

Yeah, as part of plugin_manager, lpm itself is an optional dependency. It'll allow you to say no, and use the system lpm if available, but just in case you're packing things to be portable it offers you the option.

**Comment by sbradnick** [comment]
> Also this
>> Going back to commit from last release timeframe, more current ones exhibit high CPU usage and poor UI rendering speed

> from the package changelog looks interesting (and highlight the issue I have with such a package). Would you mind expanding on it in a new issue?

I've updated to `lite-xl-2.1.1+git20230805.3979730` and I don't see any slowdowns (and they were painfully noticeable); so it was either something from my -colors,-plugins,-widgets packages, just some transient oddity in some other openSUSE package, or a problem that existed around Jul 10th -> Jul 13th up to `lite-xl-2.1.1+git20230710.76f23a2`.

**Comment by sbradnick** [comment]
> Anyways, the additions to nonicons you're doing in the package look good, are you interested in opening a pull request?

Hopefully this is useful :smile: ==> https://github.com/lite-xl/lite-xl-plugins/pull/278

Should end up looking something like this:

![2023-08-10-201821_194x176_scrot](https://github.com/lite-xl/lite-xl-plugins/assets/84082961/a9d8e945-70b3-4416-bcdf-f7e3005650f4)
