### ISSUE TITLE
[Bug] Minimap scrollbar does not scroll properly anymore.

### ISSUE THREAD

**Issue by aqilc** [lite-xl/lite-xl-plugins#169]
https://user-images.githubusercontent.com/32044067/208284148-ee614868-afa0-4a97-a041-bf63da86b568.mp4

It lags behind my cursor, the previous behavior was it staying under my cursor.

**Comment by BartolomeyKant** [comment]
I didn't know it must scroll like that. For me it's just highlight current area on hover and nothing. All clicks are propagated to main editor area and just position caret in new pos.

**Comment by BartolomeyKant** [comment]
like this
https://github.com/user-attachments/assets/def32b15-0e63-4b5a-8a32-f5b8677c5571
