### ISSUE TITLE
[Request] Dummy Text Plugin

### ISSUE THREAD

**Issue by ghost** [lite-xl/lite-xl-plugins#17]
I don't know if _dummy text_ feature already exist or not. But I try to type `lorem` and press `tab` it is doesn't do anything. This feature are like on VSCode. 
It would be nice to have a _dummy text_ plugin like `lorem ipsum` generator for add some of content on our code **if this is not available yet**.
Thank you.

**Comment by adamharrison** [comment]
Oh, interesting. I like it. Should be fairly straightforward to implement. So basically you type lorem, then every time you press tab it adds another word from lorem ipsum? (and presumably holding it spews out a bunch of lorem ipsum?)

**Comment by wahyuwiyoko** [comment]
Yes, like that. It will generate some random words of lorem ipsum like [this web generator](https://loremipsum.io/) every time you type `lorem` and press _tab_.

**Comment by Guldoman** [comment]
I think that VSCode includes the Emmet plugin by default, and `lorem` is just a snippet provided by it.
We should probably create a plugin similar to Emmet, but not necessarily as complex.

> So basically you type lorem, then every time you press tab it adds another word from lorem ipsum? (and presumably holding it spews out a bunch of lorem ipsum?)

That's not the behavior in VSCode. It just spews the entire lorem snippet at once.

**Comment by Titousensei** [comment]
https://github.com/sheetcoder/lorem is listed in the README and it looks like it matches the requirements. We should close this issue.
