### ISSUE TITLE
[Request] Auto indent after opening bracket 

### ISSUE THREAD

**Issue by blanch0t** [lite-xl/lite-xl-plugins#172]
In the autoinsert plugin, it would be convenient to go from `void func() {//caret here}` to 
```c
void func() {
    //caret here
}
```
by hitting ENTER. Seems easy enough and I would love to do it myself but unfortunately I don't know any Lua nor this project environment.

**Comment by SwissalpS** [comment]
My setup does exactly that. Not sure exactly which plugins make it happen though.

Bumping the topic so somebody knowledgeable can drop in the names of the plugins and close this.

**Comment by Guldoman** [comment]
`lfautoinsert` should be doing that, so I guess we can close this.
