### ISSUE TITLE
plugin bug lfautoinsert

### ISSUE THREAD

**Issue by beastehg** [lite-xl/lite-xl-plugins#174]
https://github.com/lite-xl/lite-xl-plugins/blob/master/plugins/lfautoinsert.lua
It even closes single tags and those that do not need
https://i.imgur.com/6GjFiwY.png
I found the line which is responsible for all this nonsense but I don't know regular expressions (could someone fix it)
https://i.imgur.com/60ip6bz.png

**Comment by Titousensei** [comment]
Fix is merged. Please close this issue.
