### ISSUE TITLE
[Request] Terminal inside text editor

### ISSUE THREAD

**Issue by nekoprog** [lite-xl/lite-xl-plugins#191]
Hi, I would like to make a feature request. Could you add terminal inside text editor by pressing Ctrl+T? It would be handy to run debug apps on terminal if running multiple tabs with different source location.

**Comment by adamharrison** [comment]
Yeah; this is a very common ask. It is, however, complicated to do correctly. The best project to watch that's doing this is https://github.com/ColonelPhantom/lite-xl-tmt, but it's not completely functional yet.

**Comment by Guldoman** [comment]
There is now https://github.com/adamharrison/lite-xl-terminal that should be very usable.
