### ISSUE TITLE
[Request] Add Modula-2 and Modula-3 lexer

### ISSUE THREAD

**Issue by 1997tn** [lite-xl/lite-xl-plugins#203]
I asked on Lexilla https://github.com/ScintillaOrg/lexilla/issues/125 but it will take very long for them to actually make the lexer. I know Lite XL supports custom lexers in Lua but I have no knowledge about Lua, please add the custom lexers for Modula-2 and Modula-3. Thank you.

**Comment by 1997tn** [comment]
Modula-2 source file extension: .def, .mod
Modula-3 source file extension: .i3, .m3, .ig, .mg

**Comment by 2cls0f** [comment]
Modula-2 and Modula-3 should be separate lexers. Don't merge them into just one Modula lexer like Lexilla, this is wrong. They are different languages with different source file extensions (see above).

**Comment by 1997tn** [comment]
TextAdept has an experimental lexer for Modula:

https://github.com/paaguti/textadept-modula-lexers
