### ISSUE TITLE
Spellcheck Plugin - How to configure in Linux?

### ISSUE THREAD

**Issue by stef204** [lite-xl/lite-xl-plugins#216]
How do I configure the spellcheck plugin in Linux?
I've tried a few things, the latest being downloading the word list [here](https://github.com/dwyl/english-words/blob/master/words.txt) and creating a symlink to it as `/usr/share/dict/words`
No error messages from `lite-xl` on launch but not sure this is working.
How does one get the spellcheck going? And get the misspelled words highlighted? Needs a lint plugin as well?
(I also have hunspell installed but couldn't get this to work with `xl-lite`.)

**Comment by Guldoman** [comment]
You can use `config.plugins.spellcheck.dictionary_file` to specify the path to the dictionary if you want to avoid the symlink.
By default it only works on `.txt` and markdown files `config.plugins.spellcheck.files = { "%.txt$", "%.md$", "%.markdown$" }`.

**Comment by stef204** [comment]
Thanks.  I see it working on a `txt` file.

So define the `config.plugins.spellcheck.dictionary_file` variable in `init.lua` like this?
`config.plugins.spellcheck.dictionary_file = "/some/path"` ?
Seems to work.

And I suppose I can add file extensions to the `config.plugins.spellcheck.files = { "%.txt$", "%.md$", "%.markdown$" }` statement to add types of files, etc.

**Comment by Guldoman** [comment]
Yes.

Ideally in the future we'll make it work with comments and strings in source files too.
