### ISSUE TITLE
[Request] JDTLS and snippets

### ISSUE THREAD

**Issue by pedricm** [lite-xl/lite-xl-plugins#221]
I would like to know if there are currently any  intentions to provide java language server protocol (JDTLS) and snippets integration within the autocomplete engine.

**Comment by Guldoman** [comment]
Does JDTLS not work with the [LSP plugin](https://github.com/lite-xl/lite-xl-lsp)? The plugin doesn't have a default config for it, but if you follow the README you should be able to make it work.

For snippets, we don't have a plugin yet.

**Comment by Guldoman** [comment]
We now have a `snippets` plugin.

**Comment by PerilousBooklet** [comment]
We now have `lsp_java`.
I think this issue can be closed now.

**Comment by PerilousBooklet** [comment]
Also the `jdtls` snippets are working with both the manual install and `lsp_java`.

**Comment by Guldoman** [comment]
Yeah, closing this. Feel free to reopen if it's not working for you.
