### ISSUE TITLE
linecopypaste plugin missing

### ISSUE THREAD

**Issue by Nomarian** [lite-xl/lite-xl-plugins#231]
[FAQ](https://lite-xl.com/en/about/faq) mentions linecopypaste plugin, it seems to be missing.

**Comment by Guldoman** [comment]
Ah yes, you're right. The plugin is now integrated as a core feature.
That FAQ needs to be updated a bit. What do you think @takase1121?

**Comment by takase1121** [comment]
Yes. I'll upload the updated version some time in the future.
