### ISSUE TITLE
Settings / Keybindings: updated bindings not refreshed

### ISSUE THREAD

**Issue by thdoan** [lite-xl/lite-xl-plugins#244]
When I save a new keybinding, the keybindings table is not refreshed to show the new binding. In the example below, I changed the binding for `root:close` to `ctrl+f4` but the table still shows `ctrl+w`:

![keybinding_save](https://user-images.githubusercontent.com/4110567/236429576-ff445127-0dec-4b43-8a08-741724baf7bb.gif)

This is a problem when you are updating many keybindings through the GUI. When a binding is saved, the table should be updated immediately to reflect the new binding.

**Comment by jgmdev** [comment]
So basically what you want is to re-trigger the filtering after changing a keybinding? Not sure if that is desirable by everyone since basically the binding you just edited would disappear from eyesight after changing.

I would like to hear others opinion on this.

**Comment by thdoan** [comment]
> So basically what you want is to re-trigger the filtering after changing a keybinding?

In the example above I changed `root:close` to a new binding, and the new binding is actually updated immediately (`ctrl+f4`). The problem is when you either clear the filter and re-filter, it goes back to the original binding that is no longer correct.

**Comment by jgmdev** [comment]
Ok, now I understood the issue, yeah this is a bug that needs fixing, thanks for clarifying.

**Comment by jgmdev** [comment]
This is also needed fixing directly on the widgets library, update it again and try.

**Comment by thdoan** [comment]
Fix confirmed. Thanks again 👍
