### ISSUE TITLE
Settings: scrolling page accidentally changes settings

### ISSUE THREAD

**Issue by thdoan** [lite-xl/lite-xl-plugins#246]
While trying to troubleshoot why my settings were suddenly out of whack, I found out the root cause: while scrolling up and down the Settings panel using the scrollwheel, if the mouse cursor happens to pass by a number field, the scrollwheel will increment/decrement the number instead of scrolling the page (it will go back to scrolling the page if the cursor is no longer above the number field though). In this example, I meant to be scrolling up the page, but since the cursor happens to be above the Indentation Size field, it's changing the indent size instead:

![scrollwheel](https://user-images.githubusercontent.com/4110567/236442321-7a55ca57-3e8c-4889-9d00-9dcdcf9d890e.gif)

This behavior can lead to accidental settings changes, so I hope we get an option to disable the scrollwheel's ability to change number fields just by hovering over them.

**Comment by thdoan** [comment]
Is there an approach that involves disabling mouse cursor hot tracking? This was a setting that is available in Delphi applications back in the day.

**Comment by jgmdev** [comment]
I already fixed it on the widgets code and was easier than what I remembered :D, can't commit it today, will do maybe on sunday after testing it is working normally.

**Comment by jgmdev** [comment]
On a second thought it was so easy that I pushed the change now to the widgets repo, give it a try by manually updating your widgets library and let me know.

**Comment by thdoan** [comment]
The fix is confirmed to be working now. Thank you for the quick fix!
