### ISSUE TITLE
[request] separate language plugins from the main list

### ISSUE THREAD

**Issue by thacuber2a03** [lite-xl/lite-xl-plugins#259]
I've seen it being talked in the Discord server but never seen it being tried
the language plugins take a big chunk of the main list and it's hard to see the other plugins
(I know you could just do a find in your browser but still)
maybe you could do something like
```
### Main plugins list

blah blah blah

### Syntax highlighters

| Language |
|---|
| [Lua](plugins/language_lua.lua?raw=1) |
| [C](plugins/language_c.lua?raw=1) |
etc...
```

Rendered (don't click the links, they're invalid):

------

### Syntax highlighters

| Language |
|---|
| [Lua](plugins/language_lua.lua?raw=1) |
| [C](plugins/language_c.lua?raw=1) |
| etc... |

**Comment by Guldoman** [comment]
We could put them under a spoiler too.

**Comment by ThaCuber** [comment]
why a spoiler?
I don't think language plugins have anything to do with movies. /j

**Comment by Guldoman** [comment]
Mostly to keep the page a bit tidier.

**Comment by ThaCuber** [comment]
1) how can you spoil a table
2) is the spoiled table going to be inlined with the other plugins? because that would look kind of dumb

**Comment by Guldoman** [comment]
Test:

| Plugin                                                                                                           | Description                                                                                                                                                                                                                                                                                      |
| :--------------------------------------------------------------------------------------------------------------- | :----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| [`align_carets`](plugins/align_carets.lua?raw=1)                                                                 | Align multiple carets and selections *([clip](https://user-images.githubusercontent.com/2798487/165631951-532f8d24-d596-4dd0-9d21-ff53c71ed32f.mp4))*                                                                                                                                            |
| [`autoinsert`](plugins/autoinsert.lua?raw=1)                                                                     | Automatically inserts closing brackets and quotes. Also allows selected text to be wrapped with brackets or quotes.                                                                                                                                                                              |
| [`autosave`](plugins/autosave.lua?raw=1)                                                                         | Automatically saves files when they are changed                                                                                                                                                                                                                                                  |
| [`autosaveonfocuslost`](plugins/autosaveonfocuslost.lua?raw=1)                                                   | Automatically saves files that were changed when the main window loses focus by switching to another application                                                                                                                                                                                 |
| [`autowrap`](plugins/autowrap.lua?raw=1)                                                                         | Automatically hardwraps lines when typing                                                                                                                                                                                                                                                        |
| [`bigclock`](plugins/bigclock.lua?raw=1)                                                                         | Shows the current time and date in a view with large text *([screenshot](https://user-images.githubusercontent.com/3920290/82752891-3318df00-9db9-11ea-803f-261d80d5cf53.png))*                                                                                                                  |
| [`black`](https://git.sr.ht/~tmpod/black-lite)\*                                                                 | Integrates the [black](https://github.com/psf/black) Python formatter with lite                                                                                                                                                                                                                  |
| [`bracketmatch`](plugins/bracketmatch.lua?raw=1)                                                                 | Underlines matching pair for bracket under the caret *([screenshot](https://user-images.githubusercontent.com/3920290/80132745-0c863f00-8594-11ea-8875-c455c6fd7eae.png))*                                                                                                                       |
| [`build`](https://github.com/adamharrison/lite-xl-ide.git)\*                                                     | Provides a build system, messages window, and easily clickable errors. Supports an internal build system, and `make`. *([screenshot](https://raw.githubusercontent.com/adamharrison/lite-xl-ide/main/screenshots/build.png))*                                                                    |
| [`centerdoc`](plugins/centerdoc.lua?raw=1)                                                                       | Centers document's content on the screen and adds zen mode support *([screenshot](https://user-images.githubusercontent.com/3920290/82127896-bf6e4500-97ae-11ea-97fc-ba9a552bc9a4.png))*                                                                                                         |
| [`colorpicker`](plugins/colorpicker.lua?raw=1)                                                                   | Color picker dialog that supports html and rgb notations.                                                                                                                                                                                                                                        |
| [`colorpreview`](plugins/colorpreview.lua?raw=1)                                                                 | Underlays color values (eg. `#ff00ff` or `rgb(255, 0, 255)`) with their resultant color. *([screenshot](https://user-images.githubusercontent.com/3920290/80743752-731bd780-8b15-11ea-97d3-847db927c5dc.png))*                                                                                   |

...

<details>
  <summary>Language plugins</summary>

| Plugin                                                                                                           | Description                                                                                                                                                                                                                                                                                      |
| :--------------------------------------------------------------------------------------------------------------- | :----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| [`language_angelscript`](plugins/language_angelscript.lua?raw=1)                                                 | Syntax for the [Angelscript](https://www.angelcode.com/angelscript/) programming language                                                                                                                                                                                                        |
| [`language_assembly_riscv`](plugins/language_assembly_riscv.lua?raw=1)                                           | Syntax for RISC-V assembly                                                                                                                                                                                                                                                                       |
| [`language_assembly_x86`](plugins/language_assembly_x86.lua?raw=1)                                               | Syntax for Intel x86 assembly                                                                                                                                                                                                                                                                    |
| [`language_autohotkey_v1`](plugins/language_autohotkey_v1.lua?raw=1)                                             | Syntax for the [AutoHotkey](https://www.autohotkey.com)(v1) programming language                                                                                                                                                                                                                 |
| [`language_batch`](plugins/language_batch.lua?raw=1)                                                             | Syntax for Windows [Batch Files](https://en.wikipedia.org/wiki/Batch_file)                                                                                                                                                                                                                       |
| [`language_bib`](plugins/language_bib.lua?raw=1)                                                                 | Syntax for [BibTex](https://en.wikipedia.org/wiki/BibTeX) files                                                                                                                                                                                                                                  |
| [`language_blade`](plugins/language_blade.lua?raw=1)                                                             | Syntax for [Blade](https://github.com/blade-lang/blade/) files                                                                                                                                                                                                                                   |
| [`language_caddyfile`](plugins/language_caddyfile.lua?raw=1)                                                     | Syntax for the Caddyfile used on the [Caddy](https://caddyserver.com/) web server                                                                                                                                                                                                                |
| [`language_cmake`](plugins/language_cmake.lua?raw=1)                                                             | Syntax for the CMake build system language                                                                                                                                                                                                                                                       |
| [`language_containerfile`](https://github.com/FilBot3/lite-xl-language-containerfile)\*                          | Syntax for [Containerfile](https://github.com/containers/common/blob/main/docs/Containerfile.5.md)/[Dockerfile](https://docs.docker.com/engine/reference/builder/)                                                                                                                               |
| [`language_crystal`](https://github.com/Tamnac/lite-plugin-crystal)\*                                            | Syntax for the [Crystal](https://crystal-lang.org) programming language                                                                                                                                                                                                                          |
| [`language_csharp`](plugins/language_csharp.lua?raw=1)                                                           | Syntax for the [C#](http://csharp.net) programming language                                                                                                                                                                                                                                      |

...

</details>

**Comment by ThaCuber** [comment]
ohhhhh ok I didn't get it lol

**Comment by ThaCuber** [comment]
but I can see you guys are updating the README.md automatically, how are you going to check for language plugins, just check if the plugin starts with `language_` or do something more reliable?

**Comment by Guldoman** [comment]
We could for example add a `language` tag for them, like in this example https://github.com/lite-xl/lite-xl-plugin-manager/blob/eaf74ed6bcb9ea1236e15fe8124db5081059ed8b/SPEC.md?plain=1#L177

**Comment by SwissalpS** [comment]
I would like them to be in a folder, a meta-plugin or plugin-pack (however you want to call it) The spoiler works for the webpage but when I am working on plugins I have to scroll through the bunch over and over again. Sure I can delete them, but they reapear whenever I ``git clone ...`` or ``git checkout``.

**Comment by Guldoman** [comment]
We can definitely add them to a meta-plugin, and will probably do (like we'll probably also have an `addons` meta-plugin).

I don't think we'll move them to a different directory tho, as that would break the setup for people that cloned the repo and symlinked the plugins.

**Comment by ThaCuber** [comment]
wait, so does the "addons" metaplugin imply that lite-xl addons will be no more?

**Comment by adamharrison** [comment]
No no, but it means we'll use lpm to build it probably.

**Comment by SwissalpS** [comment]
in the log, the languages also spam a lot makeing us scroll through them all to see the error message of a plugin that was supposed to be loaded before them

**Comment by Guldoman** [comment]
About that, we should probably auto-scroll to the error if the LogView opened automatically because of startup errors.

**Comment by SwissalpS** [comment]
that also brings up another point. While reading the log, if there are new messages, the log is scrolled back to the top (if I'm not mistaken)

**Comment by Guldoman** [comment]
Yep, an annoying quirk. Would you mind opening an issue about it, so we don't forget to fix that?
