### ISSUE TITLE
.zsh highlight

### ISSUE THREAD

**Issue by ravaq** [lite-xl/lite-xl-plugins#282]
Hi
I installed the 'language_sh' plugin, and it works fine in the .bashrc file, but in .zsh files it doesn't highlight syntax, what should I do to fix this?

**Comment by Guldoman** [comment]
You have two options:
1. Use the `force_syntax` plugin and select the "Shell script" language via the `force-syntax:select-file-syntax` command or by clicking on the syntax name in the status bar (bottom right of the window).
2. Change `language_sh` to include `%.zsh$` as one of the entries in the `files` field.

If you choose 2, please consider opening a PR with your changes.

**Comment by ravaq** [comment]
Thanks, num 2 works fine. I opened a PR.

**Comment by Guldoman** [comment]
Closed by #291.
