### ISSUE TITLE
[Request] Cycle/Switch between most/last recent/used tabs

### ISSUE THREAD

**Issue by Patitotective** [lite-xl/lite-xl-plugins#304]
Just like Firefox or Sublime Text, I think it would be really useful to have Ctrl+Tab cycle through the most recent tabs instead of just going to the next tab.

**Comment by Guldoman** [comment]
@Patitotective let me know if the linked PR satisfies your request.

**Comment by Patitotective** [comment]
@Guldoman It works well but it would be great if it worked like Sublime Text, where without releasing Ctrl and pressing Tab switches to the second recent tab, and pressing again switches to the third recent tab and so. I know it's more complicated but I think it would be really great.
As for the keybind I'm going to set it to Ctrl+Tab since I won't need the default Ctrl+Tab anymore.
Thank you.

**Comment by Guldoman** [comment]
> it would be great if it worked like Sublime Text, where without releasing Ctrl and pressing again Tab (considering Ctrl+Tab was the shortcut) switches to the second recent tab, and pressing Tab once again switches to the third recent tab and so on.

Mmm, I'll have to think about how to best implement this, as it doesn't map well to our commands system.

**Comment by Guldoman** [comment]
@Patitotective I implemented the "hold" mode in the linked PR.
Would you mind checking how it works out for you?

**Comment by Patitotective** [comment]
@Guldoman It works perfectly for me, thank you. Should I close this issue?
