### ISSUE TITLE
search_ui's replace button is expanding and causing a scroll

### ISSUE THREAD

**Issue by felixsanz** [lite-xl/lite-xl-plugins#335]
![1699464662](https://github.com/lite-xl/lite-xl-plugins/assets/6182099/344a71e2-e4f0-410f-a4d5-327ce2b3e1ac)

**Comment by jgmdev** [comment]
Just in case, some time ago I added various fixes to the search ui here, https://github.com/pragtical/pragtical/blob/master/data/plugins/search_ui.lua if using lite-xl you would need to port them and maybe PR them on this repo.
