### ISSUE TITLE
Setting GUI - Installed Nerd Fonts cant be selected

### ISSUE THREAD

**Issue by ranjandatta** [lite-xl/lite-xl-plugins#357]
Installed Nerd fonts from AUR dont show up in font selection GUI
![nerd font](https://github.com/lite-xl/lite-xl-plugins/assets/136195473/716417b8-5d4e-47eb-9ef6-cc1565792fc9)

**Comment by jgmdev** [comment]
General -> Clear Fonts Cache

**Comment by ranjandatta** [comment]
Thanks! That worked!
