### ISSUE TITLE
Please add color preview feature or make a plugin for that

### ISSUE THREAD

**Issue by tasinone** [lite-xl/lite-xl-plugins#359]
Can you add the color preview feature, please? So that if we write a color code or name then it shows the color like the plugin below.

plugin link: https://marketplace.visualstudio.com/items?itemName=kamikillerto.vscode-colorize

**Comment by adamharrison** [comment]
I believe this exists here: https://github.com/lite-xl/lite-xl-plugins/blob/master/plugins/colorpreview.lua.
