### ISSUE TITLE
[Issue] Smoothcaret breaks multi-cursor rendering 

### ISSUE THREAD

**Issue by Domant3lis** [lite-xl/lite-xl-plugins#45]
When smoothcaret is enabled, only one caret appears when trying to use multi-cursor functionality.  

This is how it looks:
![bad](https://user-images.githubusercontent.com/49041398/158870787-4ad0de5c-8992-483d-9b21-8d954c522a85.gif)

Normally it looks like this:
![good](https://user-images.githubusercontent.com/49041398/158870798-ba3bbaae-5987-40e6-a02a-df1f37fe77ad.gif)

System: i7-1165G7, Mesa Intel® Xe Graphics (TGL GT2) (Mesa version: 21.3.7)
OS: Fedora Linux 35 (Gnome 41.3 on Wayland)
Lite XL version: 2.0.5 ([from the binary releases page](https://github.com/lite-xl/lite-xl/releases/download/v2.0.5/lite-xl-linux-x86_64.tar.gz))

**Comment by Guldoman** [comment]
Thank you for the report!

Could you please test if #46 fixes your problem?

**Comment by Domant3lis** [comment]
Sure, I'll test it when I can (probably tomorrow).
