### ISSUE TITLE
Add plugin to show trailing whitespace

### ISSUE THREAD

**Issue by ieeemma** [lite-xl/lite-xl-plugins#53]
It would be helpful to visualize trailing whitespace by highlighting it in red, maybe as an overlayed color or as an underline using [lint+](https://github.com/liquidev/lintplus).

**Comment by Guldoman** [comment]
What do you think about lite-xl/lite-xl#908? Any other option you'd like to see?
Keep in mind, that PR only applies to the future `2.1` version and up.

**Comment by Titousensei** [comment]
`drawwhitespace` is very good with improvements 908, but the options are hidden in the code. It would be nice to have those options in the config editor.

**Comment by adamharrison** [comment]
I'd say open that issue on the primary lite-xl repo if you want to persue it @Titousensei .
