### ISSUE TITLE
CPP language plugin does not handle demarcations

### ISSUE THREAD

**Issue by Joshua-Ashton** [lite-xl/lite-xl-plugins#64]
You can write numbers like `1'000` to ease readability, the language plugin does not handle this well:

![image](https://user-images.githubusercontent.com/21316711/163896535-8c0254c4-0f39-4f47-a935-d96b90b21e93.png)

**Comment by Guldoman** [comment]
Updated `language_cpp` to match the one from lite-xl/lite-xl in 2fc43f72ad0ddd6ca7243d56fc2bac47caa475db.
