### ISSUE TITLE
discord-presence -> litepresence

### ISSUE THREAD

**Issue by ShadiestGoat** [lite-xl/lite-xl-plugins#75]
discord-presence says litepresence is the replacement

**Comment by Guldoman** [comment]
It looks like `litepresence` doesn't replace `discord-presence` in all cases as noted in vincens2005/lite-xl-discord@8be77a01ce20b571374826269a1e39433bb47e1a so I'll leave the decision to @vincens2005.

**Comment by vincens2005** [comment]
litepresence is the replacement, unless you're on linux using future releases (or the master branch). We should keep both but maybe put "recommended in most cases" or something like that on litepresence
