### ISSUE TITLE
selectionhighlight doesn't higlight same line matches

### ISSUE THREAD

**Issue by ShadiestGoat** [lite-xl/lite-xl-plugins#76]
When theres matches on the line of the selection, it ignores them?

![image](https://user-images.githubusercontent.com/48590492/165004937-791ec458-ca7e-478d-a9b8-98901acbf21a.png)

**Comment by Guldoman** [comment]
Fixed by 9e15d93909096a14b43fc8e2e098ba9ef734e166.
