### ISSUE TITLE
Please included drawwhitespace from rxi/lite-plugins

### ISSUE THREAD

**Issue by sheetcoder** [lite-xl/lite-xl-plugins#82]
Kindly add [drawwhitespace](https://raw.githubusercontent.com/rxi/lite-plugins/master/plugins/drawwhitespace.lua) form rxi/lite-plugins here.

**Comment by Guldoman** [comment]
The functionality is included by default on 2.0.5 and can be enabled by setting `config.draw_whitespace=true` in your user module.
