### ISSUE TITLE
Put all `language_xxxx.lua` files inside language folder 

### ISSUE THREAD

**Issue by sheetcoder** [lite-xl/lite-xl-plugins#83]
Readme has become very crowded and to organize it better my suggestion is that we move all raw `language_xxxx.lua` files to `/plugins/language/`

**Comment by adamharrison** [comment]
Due to the way the plugin infrastructure works, it makes sense to keep them in the same folder; but we could definitely do the README better.  Will look into packing grouping into the `lpm` table generator.
