### ISSUE TITLE
Wrap text

### ISSUE THREAD

**Issue by maroozm** [lite-xl/lite-xl-plugins#90]
Is there any way to wrap text automatically on a long line? Otherwise, I have to put an Enter, which makes the code really inconsistent.

**Comment by adamharrison** [comment]
Yes,  this is part of 2.1 (see the branch here: https://github.com/lite-xl/lite-xl/pull/897). If you build it, you should be able to enable line wrap with F10.

**Comment by offsounder** [comment]
I noticed an issue with this plugin (2.1 branch, with lite 2.1 pre-release).

When I check 'enable by default' in the line-wrapping plugin settings, the next time I open lite-xl, it crashes. Here is the error.txt.

```
 GNU nano 6.0                /home/daron/.config/lite-xl/error.txt                           
Error: /home/daron/.opt/lite-xl/data/plugins/linewrapping.lua:224: attempt to perform arithme>
stack traceback:
       .../lite-xl/data/plugins/linewrapping.lua:224: in function 'plugins.line>
       .../lite-xl/data/plugins/linewrapping.lua:364: in function 'core.docview>
       .../lite-xl/data/widget/textbox.lua:27: in method 'new'
        .../lite-xl/data/core/object.lua:54: in function 'widget.button.__call'
        .../lite-xl/data/widget/textbox.lua:117: in function 'widget.textbox.new'
        .../lite-xl/data/core/object.lua:54: in function 'widget.button.__call'
        .../lite-xl/data/widget/numberbox.lua:35: in function 'widget.numberbox.>
        .../lite-xl/data/core/object.lua:54: in function 'widget.button.__call'
        .../lite-xl/data/plugins/settings.lua:1061: in upvalue 'add_control'
        .../lite-xl/data/plugins/settings.lua:1262: in method 'load_core_setting>
        .../lite-xl/data/plugins/settings.lua:1025: in method 'new'
        .../lite-xl/data/core/object.lua:54: in function 'widget.button.__call'
        .../lite-xl/data/plugins/settings.lua:1775: in function 'core.run'
        (...tail calls...)
        [string "local core..."]:9: in function <[string "local core..."]:2>
        [C]: in function 'xpcall'
        [string "local core..."]:2: in main chunk
```

**Comment by jgmdev** [comment]
> I noticed an issue with this plugin (2.1 branch, with lite 2.1 pre-release).
> 
> When I check 'enable by default' in the line-wrapping plugin settings, the next time I open lite-xl, it crashes. Here is the error.txt.

This is the same issue reported on https://github.com/lite-xl/lite-xl/issues/1158 

Fixed it directly on the widget textbox so upgrading the widget library will also tackle this issue.

**Comment by mcabbott** [comment]
Is there a way that line wrapping could disable horizontal scrolling?

There is nothing to see out there, but with a trackpad it's easy to accidentally go slightly diagonally.

**Comment by adamharrison** [comment]
Yeah, this can be done. I'll make a PR.

**Comment by Guldoman** [comment]
This should be enough:
```lua
local DocView = require "core.docview"

local old_get_h_scrollable_size = DocView.get_h_scrollable_size
function DocView:get_h_scrollable_size(...)
  if self.wrapping_enabled then return 0 end
  return old_get_h_scrollable_size(self, ...)
end
```

**Comment by adamharrison** [comment]
Yeah; you wanna just PR that into the linewrapping plugin?

**Comment by Guldoman** [comment]
Sure, lite-xl/lite-xl#1309.
